name: Publish to npm with Version Bump

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Bump Version and Publish
        run: |
          # Bump version (e.g., patch, minor, major)
          npm version patch --force -m "Bump version to %s [skip ci]"

          # Publish to npm
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
