name: Publish to npm with Version Bump

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Set up Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Bump version
        run: |
          # Bump version
          npm version patch

          # Check changes
          git diff --stat

          # Commit changes to package.json
          git add .
          git commit -m "Bump version in package.json CI/CD"

      - name: Push changes
        run: |
          git push origin main

      - name: Publish to npm
        run: npm publish --access public
        env:
          NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
